[package]
name = "wooting-analog-wrapper"
version = "0.6.0"
authors = ["simon-wh <simon@wooting.io>"]
edition = "2018"

[dependencies]
lazy_static = "*"
libloading = "^0.5"
wooting-analog-common = { path = "../wooting-analog-common", features = ["python"]}
ctrlc = { version = "3", features = ["termination"] }

[dependencies.pyo3]
version = "0.14.2"
features = ["extension-module", "serde"]

[lib]
name = "wooting_analog_wrapper"
crate-type = ["cdylib", "rlib", "staticlib"]

[features]
serdes = ["wooting-analog-common/serdes"]
